version: "3.8"
services:
  db:
    image: mongo:7.0
    container_name: tkart-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tkartdb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: tkart-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
